# Generated by Django 6.1.1 on 2026-09-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название номера')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена за ночь')),
                ('guests', models.IntegerField(verbose_name='Количество гостей')),
                ('area', models.IntegerField(verbose_name='Площадь (м²)')),
                ('image', models.ImageField(upload_to='rooms/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
    ]
